name: Autofac Events Build

on: [push]

#dotnet /app/GitVersion.dll > .gitversion.json


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Get Git Version
      id: gitversion
      uses: docker://gittools/gitversion:latest      
      # with:
      #   args: "'> .gitversion.json'"
    - name: Dump Git Version
      run: echo ${{ toJSON(steps) }}
    # - name: Dump Git Version
    #   run:  cat ./.gitversion.json
      #run: jq .NuGetVersionV2 ./.gitversion.json
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.100
    - name: Debug Dump
      run: echo "::warning::${{ toJSON(github) }}"
    - name: Build
      run: dotnet build --configuration Release
    - name: Pack
      run: dotnet pack --configuration Release -p:Version=${{ steps.gitversion.outputs.FullSemVer }} -o "./packages"
    - name: Publish
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}
      run: dotnet nuget push -s https://www.nuget.org/api/v2/package -k $NUGET_AUTH_TOKEN ./packages/*.nupkg